services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ../..:/workspaces:cached
